# Generated by Django 4.1.5 on 2023-01-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPTSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=2)),
                ('top_p', models.DecimalField(decimal_places=2, max_digits=3)),
                ('model', models.CharField(max_length=255)),
                ('num_tokens', models.IntegerField()),
                ('response_name', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=10000)),
            ],
        ),
    ]
