# Generated by Django 4.1.5 on 2023-01-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPTSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('temperature', models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ('top_p', models.DecimalField(decimal_places=2, default=0.9, max_digits=3)),
                ('model', models.CharField(max_length=255)),
                ('num_tokens', models.IntegerField()),
                ('response_name', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(max_length=1000)),
                ('n', models.PositiveSmallIntegerField(default=1)),
                ('size', models.CharField(default='1024x1024', max_length=9)),
                ('response_format', models.CharField(default='url', max_length=12)),
            ],
        ),
    ]
