# Generated by Django 4.1.5 on 2023-05-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gptsub",
            name="num_tokens",
        ),
        migrations.AlterField(
            model_name="gptsub",
            name="response",
            field=models.TextField(),
        ),
    ]
