# Generated by Django 4.1.5 on 2023-05-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0003_gptsub_tokens_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gptsub",
            name="tokens_used",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
