# Generated by Django 4.1.5 on 2023-05-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0004_alter_gptsub_tokens_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="gptsub",
            name="prompt_tokens",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="gptsub",
            name="response_tokens",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
