# Generated by Django 4.1.5 on 2023-12-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0005_gptsub_prompt_tokens_gptsub_response_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageprompt",
            name="model",
            field=models.CharField(default="dall-e-3", max_length=10),
        ),
        migrations.AddField(
            model_name="imageprompt",
            name="quality",
            field=models.CharField(default="standard", max_length=10),
        ),
        migrations.AddField(
            model_name="imageprompt",
            name="style",
            field=models.CharField(default="vivid", max_length=10),
        ),
    ]
